### ISSUE TITLE
P-value adjustment about Cell-Cell Interaction Analysis

### ISSUE THREAD

**Issue by LipingChen0607** [BiomedicalMachineLearning/stlearn_interactive#15]
Dear developer,
I'm confused about the P-value adjustment in Cell-Cell Interaction Analysis.
Could you help me explain what 'correct_axis ' means and how to set this parameter in different conditions?
I have run Cell-Cell Interaction Analysis based on 'correct_axis'=None/spot/LR, and the data.uns['lr_summary'] in these three results seems different. 
Could you tell me the meaning of 'n_spots_sig_pval' in data.uns['lr_summary']? 
Thank you very much!
<img width="497" alt="截屏2022-08-22 上午10 46 42" src="https://user-images.githubusercontent.com/74603389/185829140-9f304095-d33b-48bc-a522-882e6b0b418e.png">

**Comment by BradBalderson** [comment]
Hi @LipingChen0607 ,

I'm a little confused, we discussed this in the other thread? Here:

https://github.com/BiomedicalMachineLearning/stLearn/issues/185

Also is an stLearn, rather than stLearn interactive, question, so will close here and refer to above thread.
